### ISSUE TITLE
Question about how the extension of the downloaded file is chosen

### ISSUE THREAD

**Issue by Elcoid** [gilcu3/hullcaster#5]
Hello,

This is a question about lines 82 to 89 in `src/download.rs`, which come from the original Shellcaster.

I was wondering if you know why the extension of the downloaded file is determined from the MIME type instead of simply from the URL of the file. I came across this part of the code when I had problems with a podcast that publishes its episodes in the opus format. They were saved with `.mp3` instead of `.opus` because unknown formats default to mp3.

If you're interested, I changed the behaviour in my fork of Shellcaster. The change is in this commit: https://github.com/Elcoid/shellcaster-classic/commit/5f3b3151cdcfe5f20dc027459e83abfb8d6a0060

**Comment by gilcu3** [comment]
Hi @Elcoid, thanks for the heads-up. I think MIME types are the preferred way of identifying file types on the web, see for example this answer [link](https://serverfault.com/questions/169442/why-are-mime-types-needed-if-we-can-identify-file-types-by-their-extensions). If you are willing to make a PR I will be glad to add it. Otherwise, I will cherry-pick your commit at some point in the future, although I think the best would be to find a crate to handle this type of thing.

**Comment by gilcu3** [comment]
Makes sense. BTW when you make the PR, do it on the developer branch, I am trying to keep development as organized as possible :)

**Comment by gilcu3** [comment]
Solved my #6
